version: '2'

services:
  drone-server:
    image: drone/drone:0.7.3
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true # ユーザ登録有効化
      - DRONE_HOST=${DRONE_HOST} # ホストのIP
      - DRONE_GITHUB=true # Github有効化
    #  - DRONE_GITHUB_URL=${DRONE_GITHUB_URL} # Github Enterpriseを使用している場合に設定
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT} # github Auth認証
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET} # github Auth認証
      - DRONE_SECRET=${DRONE_SECRET} # ユニークな文字列
      - DRONE_GITHUB_PRIVATE_MODE=false # Github Enterpriseをプライベートモードで動かしている場合、true

  drone-agent:
    image: drone/drone:0.7.3
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}